// Generated by scripts/generate-additional-code.mjs from the actual React demos.
import type { CodeBundle } from "./catalog";
const styles = `.modern-demo {
  --demo-bg: light-dark(#fff, #1b1b1d);
  --demo-panel: light-dark(#fff, #232428);
  --demo-panel-strong: light-dark(#edf0f5, #2a2a2d);
  --demo-line: light-dark(#dfe3ea, #414753);
  --demo-text: light-dark(#252b35, #f3f3f4);
  --demo-muted: light-dark(#596474, #b8b8bd);
  --demo-blue: #2458d3;
  display: grid;
  gap: 12px;
  width: min(100%, 360px);
  min-width: 0;
  container-type: inline-size;
  padding: 18px;
  color: var(--demo-text);
  background: var(--demo-panel);
  border: 1px solid var(--demo-line);
  border-radius: 12px;
  font:
    14px/1.5 system-ui,
    sans-serif;
}
.modern-demo *,
.modern-demo *::before,
.modern-demo *::after {
  box-sizing: border-box;
}
.modern-demo [hidden] {
  display: none !important;
}
.modern-demo button,
.modern-demo input {
  font: inherit;
}
.modern-demo button {
  min-height: 44px;
  border: 1px solid var(--demo-line);
  border-radius: 7px;
  background: var(--demo-panel-strong);
  color: var(--demo-text);
  padding: 8px 12px;
  cursor: pointer;
}
.modern-demo button:hover {
  border-color: var(--demo-blue);
}
.modern-demo button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
.modern-demo :focus-visible {
  outline: 2px solid light-dark(#2458d3, #8aafff);
  outline-offset: 3px;
}
.modern-demo p {
  margin: 0;
}
.modern-demo > p {
  font-size: 12px;
  color: var(--demo-muted);
}
.modern-demo input:not([type="checkbox"], [type="radio"]) {
  display: block;
  width: 100%;
  min-width: 0;
  min-height: 44px;
  background: var(--demo-bg);
  color: var(--demo-text);
  border: 1px solid var(--demo-line);
  border-radius: 7px;
  padding: 8px 10px;
}
.modern-demo input[aria-invalid="true"] {
  border-color: light-dark(#bc3548, #ed7683);
}
.modern-kicker {
  font-size: 12px;
  font-weight: 650;
  color: var(--demo-muted);
}
.modern-actions {
  display: flex;
  gap: 6px;
  flex-wrap: wrap;
}
.modern-date-row {
  display: grid;
  grid-template-columns: minmax(0, 1fr) auto minmax(0, 1fr);
  align-items: end;
  gap: 6px;
}
.modern-date-row label {
  font-size: 12px;
  min-width: 0;
}
.modern-date-row > span {
  padding-bottom: 12px;
}
.modern-options,
.modern-rating {
  margin: 0;
  padding: 0;
  border: 0;
  min-width: 0;
}
.modern-options legend,
.modern-rating legend {
  margin-bottom: 10px;
  font-weight: 600;
}
.modern-options {
  display: flex;
  flex-wrap: wrap;
  gap: 6px 12px;
}
.modern-options label {
  display: flex;
  min-height: 36px;
  gap: 6px;
  align-items: center;
}
.modern-options input {
  accent-color: var(--demo-blue);
  width: 16px;
  height: 16px;
}
.modern-rating > div {
  display: flex;
  overflow-x: auto;
}
.modern-rating label {
  position: relative;
  display: grid;
  place-items: center;
  flex: 0 0 44px;
  min-width: 44px;
  height: 48px;
  font-size: 34px;
  color: var(--demo-muted);
  cursor: pointer;
}
.modern-rating label[data-filled="true"] {
  color: light-dark(#a2670e, #e9ad58);
}
.modern-rating input {
  position: absolute;
  inset: 0;
  margin: 0;
  width: 100%;
  height: 100%;
  opacity: 0;
  cursor: pointer;
}
.modern-rating label:focus-within {
  outline: 2px solid light-dark(#2458d3, #8aafff);
  border-radius: 7px;
}
.modern-menubar {
  display: flex;
  gap: 4px;
  position: relative;
  z-index: 2;
}
.modern-menubar > div {
  position: relative;
}
.modern-menubar [data-menu-trigger] {
  padding-inline: 8px;
}
.modern-menubar [data-menu-popup] {
  position: absolute;
  top: 100%;
  left: 0;
  min-width: 132px;
  padding: 4px;
  background: var(--demo-panel);
  border: 1px solid var(--demo-line);
  border-radius: 8px;
  box-shadow: 0 8px 20px rgb(0 0 0 / 0.12);
}
.modern-menubar > div:last-child [data-menu-popup] {
  left: auto;
  right: 0;
}
.modern-menubar [data-menu-popup] button {
  width: 100%;
  border: 0;
  text-align: left;
  background: transparent;
}
.modern-menubar [data-menu-popup] button:focus,
.modern-menubar [data-menu-popup] button:hover {
  background: var(--demo-panel-strong);
}
.modern-editor {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  padding: 20px;
  background: var(--demo-panel-strong);
  border-radius: 6px;
  font-size: 32px;
}
.modern-editor span {
  font-size: 12px;
  color: var(--demo-muted);
}
.modern-message {
  justify-self: end;
  max-width: 90%;
  padding: 12px 16px;
  border-radius: 12px 12px 3px 12px;
  background: var(--demo-panel-strong);
  overflow-wrap: anywhere;
}
.modern-message small {
  color: var(--demo-muted);
}
.modern-message-form {
  display: flex;
  gap: 6px;
}
.modern-message-form button {
  flex-shrink: 0;
  background: var(--demo-blue);
  color: white;
}
.modern-transcript {
  height: 130px;
  overflow-y: auto;
  overscroll-behavior: contain;
  scrollbar-width: thin;
  overflow-anchor: none;
}
.modern-transcript > p {
  padding: 10px;
  margin-bottom: 6px;
  background: var(--demo-panel-strong);
  border-radius: 6px;
}
.modern-transcript small {
  display: block;
  color: var(--demo-muted);
  font-size: 11px;
}
.modern-attachment {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 10px;
  border: 1px solid var(--demo-line);
  border-radius: 8px;
}
.modern-attachment > div {
  flex: 1;
  min-width: 0;
}
.modern-attachment strong {
  display: block;
  font-size: 13px;
  overflow-wrap: anywhere;
}
.modern-attachment small {
  display: block;
  color: var(--demo-muted);
  font-size: 11px;
}
.modern-filetype {
  background: var(--demo-panel-strong);
  border-radius: 4px;
  padding: 12px 6px;
  font-size: 10px;
  font-weight: 700;
}
.demo-stage--card .modern-demo {
  padding: 12px;
  gap: 8px;
  font-size: 12px;
}
.demo-stage--card:has(.modern-demo) .demo-canvas {
  padding: 12px;
  height: 100%;
  overflow-y: auto;
  align-content: safe center;
}
.demo-stage--card .modern-demo > .modern-kicker {
  display: none;
}
.demo-stage--card .modern-demo button {
  min-height: 36px;
  padding: 6px 10px;
}
.demo-stage--card .modern-demo input:not([type="checkbox"], [type="radio"]) {
  min-height: 36px;
  padding: 6px;
}
.demo-stage--card .modern-transcript {
  height: 88px;
}
.demo-stage--card .modern-options label {
  min-height: 28px;
}
.demo-stage--card .modern-date-row {
  grid-template-columns: minmax(0, 1fr);
  gap: 4px;
}
.demo-stage--card .modern-date-row > span {
  display: none;
}
.demo-stage--card .modern-date-row label {
  display: grid;
  grid-template-columns: 50px minmax(0, 1fr);
  align-items: center;
}
@container (max-width: 280px) {
  .modern-date-row {
    grid-template-columns: minmax(0, 1fr);
  }
  .modern-date-row > span {
    display: none;
  }
}
`;
export const additionalCode: Record<string, CodeBundle> = {
  "date-range-picker": {
    vanilla: [
      { name: "index.html", language: "html", code: `<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <section class="modern-demo">
      <label>开始日期<input id="start" type="date" value="2026-09-05" /></label
      ><label
        >结束日期<input
          id="end"
          type="date"
          value="2026-09-12"
          min="2026-09-05"
          aria-describedby="status"
      /></label>
      <div class="modern-actions">
        <button data-days="7">7 天</button><button data-days="30">30 天</button>
      </div>
      <p id="status" role="status"></p>
    </section>
    <script src="script.js" defer></script>
  </body>
</html>
` },
      { name: "styles.css", language: "css", code: styles },
      { name: "script.js", language: "js", code: `const start = document.querySelector("#start");
const end = document.querySelector("#end");
const status = document.querySelector("#status");
function update() {
  end.min = start.value;
  const invalid = Boolean(start.value && end.value && end.value < start.value);
  end.setAttribute("aria-invalid", String(invalid));
  status.textContent = invalid
    ? "结束日期不能早于开始日期"
    : start.value && end.value
      ? start.value + " — " + end.value
      : "请选择完整日期范围";
}
start.addEventListener("input", update);
end.addEventListener("input", update);
document.querySelectorAll("[data-days]").forEach((button) =>
  button.addEventListener("click", () => {
    if (!start.value) return;
    const date = new Date(start.value + "T12:00:00Z");
    date.setUTCDate(date.getUTCDate() + Number(button.dataset.days) - 1);
    end.value = date.toISOString().slice(0, 10);
    update();
  }),
);
update();
` },
    ],
    react: [
      { name: "Component.jsx", language: "jsx", code: `import { useEffect, useId, useRef, useState } from "react";
import "./styles.css";

export default function DateRangeDemo() {
  const id = useId();
  const [start, setStart] = useState("2026-09-05");
  const [end, setEnd] = useState("2026-09-12");
  const invalid = Boolean(start && end && end < start);
  return (
    <div className="modern-demo">
      <div className="modern-kicker">报表时间范围</div>
      <div className="modern-date-row">
        <label>
          开始日期
          <input
            type="date"
            value={start}
            onChange={(event) => setStart(event.target.value)}
          />
        </label>
        <span aria-hidden="true">→</span>
        <label>
          结束日期
          <input
            type="date"
            value={end}
            min={start}
            aria-invalid={invalid}
            aria-describedby={\`\${id}-status\`}
            onChange={(event) => setEnd(event.target.value)}
          />
        </label>
      </div>
      <div className="modern-actions">
        {[7, 30].map((days) => (
          <button
            key={days}
            type="button"
            disabled={!start}
            onClick={() => {
              const date = new Date(\`\${start}T12:00:00Z\`);
              date.setUTCDate(date.getUTCDate() + days - 1);
              setEnd(date.toISOString().slice(0, 10));
            }}
          >
            {days} 天
          </button>
        ))}
      </div>
      <p id={\`\${id}-status\`} role="status">
        {invalid
          ? "结束日期不能早于开始日期"
          : start && end
            ? \`\${start} — \${end}\`
            : "请选择完整的日期范围"}
      </p>
    </div>
  );
}
` },
      { name: "styles.css", language: "css", code: styles },
    ],
  },
  "time-field": {
    vanilla: [
      { name: "index.html", language: "html", code: `<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <section class="modern-demo">
      <label
        >预约时间<input
          id="time"
          type="time"
          min="09:00"
          max="18:00"
          step="900"
          value="09:30"
          aria-describedby="status"
      /></label>
      <div class="modern-actions">
        <button data-time="09:00">09:00</button><button data-time="09:15">09:15</button
        ><button data-time="09:30">09:30</button>
      </div>
      <p id="status" role="status"></p>
    </section>
    <script src="script.js" defer></script>
  </body>
</html>
` },
      { name: "styles.css", language: "css", code: styles },
      { name: "script.js", language: "js", code: `const input = document.querySelector("#time");
function update() {
  const valid = Boolean(input.value) && input.checkValidity();
  input.setAttribute("aria-invalid", String(!valid));
  document.querySelector("#status").textContent = valid
    ? input.value + " · 上海时间 / UTC+8"
    : "请选择 09:00 至 18:00，每 15 分钟一个时段";
}
input.addEventListener("input", update);
document.querySelectorAll("[data-time]").forEach((button) =>
  button.addEventListener("click", () => {
    input.value = button.dataset.time;
    update();
  }),
);
update();
` },
    ],
    react: [
      { name: "Component.jsx", language: "jsx", code: `import { useEffect, useId, useRef, useState } from "react";
import "./styles.css";

export default function TimeFieldDemo() {
  const [time, setTime] = useState("09:30");
  const id = useId();
  const valid =
    time >= "09:00" && time <= "18:00" && Number(time.split(":")[1]) % 15 === 0;
  return (
    <div className="modern-demo">
      <label className="modern-kicker" htmlFor={id}>
        预约时间
      </label>
      <input
        id={id}
        type="time"
        min="09:00"
        max="18:00"
        step="900"
        value={time}
        aria-invalid={!valid}
        aria-describedby={\`\${id}-hint\`}
        onChange={(event) => setTime(event.target.value)}
      />
      <div className="modern-actions">
        {["09:00", "09:15", "09:30"].map((value) => (
          <button
            type="button"
            key={value}
            aria-pressed={time === value}
            onClick={() => setTime(value)}
          >
            {value}
          </button>
        ))}
      </div>
      <p id={\`\${id}-hint\`} role="status">
        {valid
          ? \`\${time} · 上海时间 / UTC+8\`
          : "请选择 09:00 至 18:00，每 15 分钟一个时段"}
      </p>
    </div>
  );
}
` },
      { name: "styles.css", language: "css", code: styles },
    ],
  },
  "multi-select": {
    vanilla: [
      { name: "index.html", language: "html", code: `<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <section class="modern-demo">
      <input id="search" type="search" aria-label="搜索团队" placeholder="搜索团队" />
      <fieldset class="modern-options">
        <legend>参与团队</legend>
        <label><input type="checkbox" value="设计" checked />设计</label
        ><label><input type="checkbox" value="研发" />研发</label
        ><label><input type="checkbox" value="产品" />产品</label
        ><label><input type="checkbox" value="研究" />研究</label>
      </fieldset>
      <div id="selected" class="modern-actions" aria-label="已选团队"></div>
      <p id="status" role="status"></p>
    </section>
    <script src="script.js" defer></script>
  </body>
</html>
` },
      { name: "styles.css", language: "css", code: styles },
      { name: "script.js", language: "js", code: `const inputs = [...document.querySelectorAll("input[type=checkbox]")];
function update() {
  const selected = inputs.filter((input) => input.checked);
  const buttons = selected.map((input) => {
    const button = document.createElement("button");
    button.textContent = input.value + " ×";
    button.setAttribute("aria-label", "移除" + input.value);
    button.onclick = () => {
      input.checked = false;
      update();
      document.querySelector("#search").focus();
    };
    return button;
  });
  document.querySelector("#selected").replaceChildren(...buttons);
  document.querySelector("#status").textContent = "已选 " + selected.length + " 个团队";
}
inputs.forEach((input) => input.addEventListener("change", update));
document.querySelector("#search").addEventListener("input", (event) => {
  inputs.forEach((input) => {
    input.parentElement.style.display = input.value.includes(event.target.value)
      ? ""
      : "none";
  });
});
update();
` },
    ],
    react: [
      { name: "Component.jsx", language: "jsx", code: `import { useEffect, useId, useRef, useState } from "react";
import "./styles.css";

export default function MultiSelectDemo() {
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState(["设计"]);
  const options = ["设计", "研发", "产品", "研究"];
  const search = useRef(null);
  return (
    <div className="modern-demo">
      <input
        ref={search}
        aria-label="搜索团队"
        placeholder="搜索团队…"
        type="search"
        value={query}
        onChange={(event) => setQuery(event.target.value)}
      />
      <fieldset className="modern-options">
        <legend>参与团队</legend>
        {options
          .filter((option) => option.includes(query))
          .map((option) => (
            <label key={option}>
              <input
                type="checkbox"
                checked={selected.includes(option)}
                onChange={() =>
                  setSelected((current) =>
                    current.includes(option)
                      ? current.filter((value) => value !== option)
                      : [...current, option],
                  )
                }
              />
              {option}
            </label>
          ))}
        {!options.some((option) => option.includes(query)) && <p>没有匹配的团队</p>}
      </fieldset>
      <div className="modern-actions" aria-label="已选团队">
        {selected.map((option) => (
          <button
            type="button"
            key={option}
            aria-label={\`移除\${option}\`}
            onClick={() => {
              setSelected((current) => current.filter((value) => value !== option));
              search.current?.focus();
            }}
          >
            {option} ×
          </button>
        ))}
      </div>
      <p role="status">已选 {selected.length} 个团队</p>
    </div>
  );
}
` },
      { name: "styles.css", language: "css", code: styles },
    ],
  },
  "rating": {
    vanilla: [
      { name: "index.html", language: "html", code: `<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <section class="modern-demo">
      <fieldset class="modern-rating">
        <legend>这次体验怎么样？</legend>
        <div>
          <label
            ><input type="radio" name="rating" value="1" aria-label="1 星" /><span
              aria-hidden="true"
              >★</span
            ></label
          ><label
            ><input type="radio" name="rating" value="2" aria-label="2 星" /><span
              aria-hidden="true"
              >★</span
            ></label
          ><label
            ><input type="radio" name="rating" value="3" aria-label="3 星" /><span
              aria-hidden="true"
              >★</span
            ></label
          ><label
            ><input type="radio" name="rating" value="4" aria-label="4 星" /><span
              aria-hidden="true"
              >★</span
            ></label
          ><label
            ><input type="radio" name="rating" value="5" aria-label="5 星" /><span
              aria-hidden="true"
              >★</span
            ></label
          >
        </div>
      </fieldset>
      <p id="status" role="status">选择 1 至 5 星评分</p>
      <button id="reset">清除评分</button>
    </section>
    <script src="script.js" defer></script>
  </body>
</html>
` },
      { name: "styles.css", language: "css", code: styles },
      { name: "script.js", language: "js", code: `const inputs = [...document.querySelectorAll("input[name=rating]")];
let value = 0;
function paint(preview = value) {
  inputs.forEach((input) => {
    input.parentElement.dataset.filled = String(Number(input.value) <= preview);
  });
}
inputs.forEach((input) => {
  input.addEventListener("change", () => {
    value = Number(input.value);
    paint();
    document.querySelector("#status").textContent = value + " / 5";
  });
  input.parentElement.addEventListener("mouseenter", () => paint(Number(input.value)));
});
document.querySelector("fieldset").addEventListener("mouseleave", () => paint());
document.querySelector("#reset").addEventListener("click", () => {
  value = 0;
  inputs.forEach((input) => (input.checked = false));
  paint();
  document.querySelector("#status").textContent = "评分已清除";
});
` },
    ],
    react: [
      { name: "Component.jsx", language: "jsx", code: `import { useEffect, useId, useRef, useState } from "react";
import "./styles.css";

export default function RatingDemo() {
  const [rating, setRating] = useState(0);
  const [preview, setPreview] = useState(0);
  const id = useId();
  return (
    <div className="modern-demo">
      <fieldset className="modern-rating" onMouseLeave={() => setPreview(0)}>
        <legend>这次体验怎么样？</legend>
        <div>
          {[1, 2, 3, 4, 5].map((value) => (
            <label
              key={value}
              data-filled={value <= (preview || rating)}
              onMouseEnter={() => setPreview(value)}
            >
              <input
                type="radio"
                name={\`\${id}-rating\`}
                aria-label={\`\${value} 星\`}
                value={value}
                checked={rating === value}
                onChange={() => setRating(value)}
              />
              <span aria-hidden="true">★</span>
            </label>
          ))}
        </div>
      </fieldset>
      <p role="status">
        {rating
          ? \`\${rating} / 5 · \${["", "有待改善", "还需打磨", "符合预期", "很满意", "非常喜欢"][rating]}\`
          : "选择 1 至 5 星评分"}
      </p>
      <button
        type="button"
        onClick={() => {
          setRating(0);
          setPreview(0);
        }}
      >
        清除评分
      </button>
    </div>
  );
}
` },
      { name: "styles.css", language: "css", code: styles },
    ],
  },
  "menubar": {
    vanilla: [
      { name: "index.html", language: "html", code: `<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <section class="modern-demo">
      <div role="menubar" aria-label="编辑器菜单" class="modern-menubar">
        <div role="none">
          <button
            id="trigger-0"
            data-menu-trigger
            role="menuitem"
            aria-haspopup="menu"
            aria-expanded="false"
            aria-controls="popup-0"
            tabindex="0"
          >
            文件
          </button>
          <div
            id="popup-0"
            data-menu-popup
            role="menu"
            aria-labelledby="trigger-0"
            hidden
          >
            <button role="menuitem" tabindex="-1">新建画板</button
            ><button role="menuitem" tabindex="-1">保存副本</button>
          </div>
        </div>
        <div role="none">
          <button
            id="trigger-1"
            data-menu-trigger
            role="menuitem"
            aria-haspopup="menu"
            aria-expanded="false"
            aria-controls="popup-1"
            tabindex="-1"
          >
            编辑
          </button>
          <div
            id="popup-1"
            data-menu-popup
            role="menu"
            aria-labelledby="trigger-1"
            hidden
          >
            <button role="menuitem" tabindex="-1">撤销操作</button
            ><button role="menuitem" tabindex="-1">复制图层</button>
          </div>
        </div>
        <div role="none">
          <button
            id="trigger-2"
            data-menu-trigger
            role="menuitem"
            aria-haspopup="menu"
            aria-expanded="false"
            aria-controls="popup-2"
            tabindex="-1"
          >
            视图
          </button>
          <div
            id="popup-2"
            data-menu-popup
            role="menu"
            aria-labelledby="trigger-2"
            hidden
          >
            <button role="menuitem" tabindex="-1">显示网格</button
            ><button role="menuitem" tabindex="-1">适合窗口</button>
          </div>
        </div>
      </div>
      <p id="status" role="status">选择一个编辑命令</p>
    </section>
    <script src="script.js" defer></script>
  </body>
</html>
` },
      { name: "styles.css", language: "css", code: styles },
      { name: "script.js", language: "js", code: `const bar = document.querySelector("[role=menubar]");
const triggers = [...bar.querySelectorAll("[data-menu-trigger]")];
let active = 0;
function close() {
  bar.querySelectorAll("[data-menu-popup]").forEach((menu) => (menu.hidden = true));
  triggers.forEach((button) => button.setAttribute("aria-expanded", "false"));
}
function top(index) {
  active = (index + triggers.length) % triggers.length;
  triggers.forEach((button, i) => (button.tabIndex = i === active ? 0 : -1));
  triggers[active].focus();
}
function open(index, last = false) {
  close();
  top(index);
  const menu = triggers[active].nextElementSibling;
  menu.hidden = false;
  triggers[active].setAttribute("aria-expanded", "true");
  const items = [...menu.querySelectorAll("[role=menuitem]")];
  items[last ? items.length - 1 : 0].focus();
}
triggers.forEach((button, index) => {
  button.onclick = () =>
    button.getAttribute("aria-expanded") === "true" ? close() : open(index);
  button.onkeydown = (event) => {
    if (["ArrowRight", "ArrowLeft", "Home", "End"].includes(event.key)) {
      event.preventDefault();
      top(
        event.key === "Home"
          ? 0
          : event.key === "End"
            ? triggers.length - 1
            : index + (event.key === "ArrowRight" ? 1 : -1),
      );
    }
    if (["ArrowDown", "ArrowUp"].includes(event.key)) {
      event.preventDefault();
      open(index, event.key === "ArrowUp");
    }
  };
  const menu = button.nextElementSibling;
  const items = [...menu.querySelectorAll("[role=menuitem]")];
  items.forEach(
    (item) =>
      (item.onclick = () => {
        document.querySelector("#status").textContent = "已执行：" + item.textContent;
        close();
        top(index);
      }),
  );
  menu.onkeydown = (event) => {
    const current = items.indexOf(document.activeElement);
    if (["ArrowDown", "ArrowUp", "Home", "End"].includes(event.key)) {
      event.preventDefault();
      const next =
        event.key === "Home"
          ? 0
          : event.key === "End"
            ? items.length - 1
            : (current + (event.key === "ArrowDown" ? 1 : items.length - 1)) %
              items.length;
      items[next].focus();
    } else if (["ArrowRight", "ArrowLeft"].includes(event.key)) {
      event.preventDefault();
      open(index + (event.key === "ArrowRight" ? 1 : -1));
    } else if (event.key === "Escape") {
      event.preventDefault();
      close();
      top(index);
    } else if (event.key === "Tab") {
      close();
      top(index);
    }
  };
});
bar.addEventListener("focusout", (event) => {
  if (!bar.contains(event.relatedTarget)) close();
});
` },
    ],
    react: [
      { name: "Component.jsx", language: "jsx", code: `import { useEffect, useId, useRef, useState } from "react";
import "./styles.css";

export default function MenubarDemo() {
  const [open, setOpen] = useState(-1);
  const [active, setActive] = useState(0);
  const [status, setStatus] = useState("选择一个编辑命令");
  const root = useRef(null);
  const firstItem = useRef(0);
  const id = useId();
  const menus = [
    { label: "文件", items: ["新建画板", "保存副本"] },
    { label: "编辑", items: ["撤销操作", "复制图层"] },
    { label: "视图", items: ["显示网格", "适合窗口"] },
  ];
  const focusTop = (index) => {
    setActive(index);
    root.current?.querySelectorAll("[data-menu-trigger]")[index]?.focus();
  };
  const focusItem = (index) => {
    const items = root.current?.querySelectorAll("[data-menu-popup] [role=menuitem]");
    if (items?.length) items[(index + items.length) % items.length]?.focus();
  };
  useEffect(() => {
    if (open >= 0) {
      const items = root.current?.querySelectorAll("[data-menu-popup] [role=menuitem]");
      if (items?.length) items[firstItem.current < 0 ? items.length - 1 : 0]?.focus();
      firstItem.current = 0;
    }
  }, [open]);
  return (
    <div
      className="modern-demo"
      ref={root}
      onBlur={(event) => {
        if (!event.currentTarget.contains(event.relatedTarget)) setOpen(-1);
      }}
    >
      <div className="modern-menubar" role="menubar" aria-label="编辑器菜单">
        {menus.map((menu, index) => (
          <div key={menu.label} role="none">
            <button
              id={\`\${id}-menu-\${index}\`}
              data-menu-trigger
              type="button"
              role="menuitem"
              aria-haspopup="menu"
              aria-expanded={open === index}
              aria-controls={open === index ? \`\${id}-popup-\${index}\` : undefined}
              tabIndex={active === index ? 0 : -1}
              onFocus={() => setActive(index)}
              onClick={() => setOpen((current) => (current === index ? -1 : index))}
              onKeyDown={(event) => {
                if (["ArrowRight", "ArrowLeft", "Home", "End"].includes(event.key)) {
                  event.preventDefault();
                  focusTop(
                    event.key === "Home"
                      ? 0
                      : event.key === "End"
                        ? 2
                        : (index + (event.key === "ArrowRight" ? 1 : 2)) % 3,
                  );
                } else if (event.key === "ArrowDown" || event.key === "ArrowUp") {
                  event.preventDefault();
                  if (open === index) focusItem(event.key === "ArrowUp" ? -1 : 0);
                  else {
                    firstItem.current = event.key === "ArrowUp" ? -1 : 0;
                    setOpen(index);
                  }
                }
              }}
            >
              {menu.label}
            </button>
            {open === index && (
              <div
                id={\`\${id}-popup-\${index}\`}
                data-menu-popup
                role="menu"
                aria-labelledby={\`\${id}-menu-\${index}\`}
                onKeyDown={(event) => {
                  const items = [
                    ...event.currentTarget.querySelectorAll("[role=menuitem]"),
                  ];
                  const current = items.indexOf(document.activeElement);
                  if (event.key === "Escape") {
                    event.preventDefault();
                    setOpen(-1);
                    focusTop(index);
                  } else if (
                    ["ArrowDown", "ArrowUp", "Home", "End"].includes(event.key)
                  ) {
                    event.preventDefault();
                    focusItem(
                      event.key === "Home"
                        ? 0
                        : event.key === "End"
                          ? -1
                          : current + (event.key === "ArrowDown" ? 1 : -1),
                    );
                  } else if (event.key === "ArrowRight" || event.key === "ArrowLeft") {
                    event.preventDefault();
                    const next = (index + (event.key === "ArrowRight" ? 1 : 2)) % 3;
                    setActive(next);
                    setOpen(next);
                  } else if (event.key === "Tab") {
                    setOpen(-1);
                    focusTop(index);
                  } else if (event.key.length === 1) {
                    const match = menu.items.findIndex((item) =>
                      item.startsWith(event.key),
                    );
                    if (match >= 0) focusItem(match);
                  }
                }}
              >
                {menu.items.map((item) => (
                  <button
                    type="button"
                    role="menuitem"
                    tabIndex={-1}
                    key={item}
                    onClick={() => {
                      setStatus(\`已执行：\${item}\`);
                      setOpen(-1);
                      focusTop(index);
                    }}
                  >
                    {item}
                  </button>
                ))}
              </div>
            )}
          </div>
        ))}
      </div>
      <div className="modern-editor" aria-hidden="true">
        Aa<span>文稿 · 01</span>
      </div>
      <p role="status">{status}</p>
    </div>
  );
}
` },
      { name: "styles.css", language: "css", code: styles },
    ],
  },
  "questionnaire": {
    vanilla: [
      { name: "index.html", language: "html", code: `<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <section class="modern-demo">
      <p id="step"></p>
      <fieldset class="modern-options">
        <legend tabindex="-1" id="question"></legend>
        <div id="answers"></div>
      </fieldset>
      <div class="modern-actions">
        <button id="back">上一步</button><button id="next">下一步</button>
      </div>
      <p id="summary" role="status"></p>
    </section>
    <script src="script.js" defer></script>
  </body>
</html>
` },
      { name: "styles.css", language: "css", code: styles },
      { name: "script.js", language: "js", code: `const questions = [
  { title: "你在设计什么？", options: ["网站", "移动应用", "桌面工具"] },
  { title: "更关注哪一方面？", options: ["视觉设计", "交互行为", "代码实现"] },
];
const answers = ["", ""];
let step = 0;
function render(focus = false) {
  const done = step === questions.length;
  document.querySelector("#step").textContent = done
    ? "问卷完成"
    : "问题 " + (step + 1) + " / 2";
  document.querySelector("#question").textContent = done ? "完成" : questions[step].title;
  document.querySelector("#answers").replaceChildren(
    ...(done
      ? []
      : questions[step].options.map((option) => {
          const label = document.createElement("label");
          const input = document.createElement("input");
          input.type = "radio";
          input.name = "answer";
          input.checked = answers[step] === option;
          input.onchange = () => {
            answers[step] = option;
            document.querySelector("#next").disabled = false;
          };
          label.append(input, option);
          return label;
        })),
  );
  document.querySelector("#back").disabled = step === 0;
  document.querySelector("#next").disabled = !done && !answers[step];
  document.querySelector("#next").textContent = done
    ? "重新填写"
    : step === 1
      ? "完成问卷"
      : "下一步";
  document.querySelector("#summary").textContent = done ? answers.join(" · ") : "";
  if (focus) document.querySelector("#question").focus();
}
document.querySelector("#back").onclick = () => {
  step -= 1;
  render(true);
};
document.querySelector("#next").onclick = () => {
  if (step === 2) {
    step = 0;
    answers.fill("");
  } else step += 1;
  render(true);
};
render();
` },
    ],
    react: [
      { name: "Component.jsx", language: "jsx", code: `import { useEffect, useId, useRef, useState } from "react";
import "./styles.css";

export default function QuestionnaireDemo() {
  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState(["", ""]);
  const heading = useRef(null);
  const previousStep = useRef(0);
  const id = useId();
  const questions = [
    { title: "你在设计什么？", options: ["网站", "移动应用", "桌面工具"] },
    { title: "更关注哪一方面？", options: ["视觉设计", "交互行为", "代码实现"] },
  ];
  const move = (next) => {
    setStep(next);
  };
  useEffect(() => {
    if (previousStep.current !== step) heading.current?.focus();
    previousStep.current = step;
  }, [step]);
  return (
    <div className="modern-demo">
      <div className="modern-kicker">
        {step < 2 ? \`问题 \${step + 1} / 2\` : "问卷完成"}
      </div>
      {step < 2 ? (
        <fieldset className="modern-options">
          <legend tabIndex={-1} ref={heading}>
            {questions[step].title}
          </legend>
          {questions[step].options.map((option) => (
            <label key={option}>
              <input
                type="radio"
                name={\`\${id}-question-\${step}\`}
                checked={answers[step] === option}
                onChange={() =>
                  setAnswers((current) =>
                    current.map((value, index) => (index === step ? option : value)),
                  )
                }
              />
              {option}
            </label>
          ))}
        </fieldset>
      ) : (
        <p role="status">你的选择：{answers.join(" · ")}</p>
      )}
      <div className="modern-actions">
        {step > 0 && (
          <button type="button" onClick={() => move(step - 1)}>
            上一步
          </button>
        )}
        {step < 2 ? (
          <button type="button" disabled={!answers[step]} onClick={() => move(step + 1)}>
            {step === 1 ? "完成问卷" : "下一步"}
          </button>
        ) : (
          <button
            type="button"
            onClick={() => {
              setAnswers(["", ""]);
              move(0);
            }}
          >
            重新填写
          </button>
        )}
      </div>
    </div>
  );
}
` },
      { name: "styles.css", language: "css", code: styles },
    ],
  },
  "chat-message": {
    vanilla: [
      { name: "index.html", language: "html", code: `<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <section class="modern-demo">
      <div class="modern-kicker">本地消息演示</div>
      <div class="modern-message">
        <small>你</small>
        <p id="message">侧边滑出的面板叫什么？</p>
      </div>
      <form class="modern-message-form">
        <input aria-label="输入消息" maxlength="160" required /><button type="submit">
          发送
        </button>
      </form>
      <button id="copy">复制消息</button>
      <p id="status" role="status">消息仅在当前演示中展示</p>
    </section>
    <script src="script.js" defer></script>
  </body>
</html>
` },
      { name: "styles.css", language: "css", code: styles },
      { name: "script.js", language: "js", code: `const input = document.querySelector("input");
const message = document.querySelector("#message");
const status = document.querySelector("#status");
document.querySelector("form").onsubmit = (event) => {
  event.preventDefault();
  if (!input.value.trim()) return;
  message.textContent = input.value.trim();
  input.value = "";
  status.textContent = "消息已发送到本地演示";
};
document.querySelector("#copy").onclick = async () => {
  try {
    await navigator.clipboard.writeText(message.textContent);
    status.textContent = "已复制消息";
  } catch {
    status.textContent = "无法复制，请手动选择消息文字";
  }
};
` },
    ],
    react: [
      { name: "Component.jsx", language: "jsx", code: `import { useEffect, useId, useRef, useState } from "react";
import "./styles.css";

export default function ChatMessageDemo() {
  const [text, setText] = useState("");
  const [message, setMessage] = useState("侧边滑出的面板叫什么？");
  const [status, setStatus] = useState("");
  return (
    <div className="modern-demo">
      <div className="modern-kicker">本地消息演示</div>
      <div className="modern-message">
        <small>你</small>
        <p>{message}</p>
      </div>
      <form
        className="modern-message-form"
        onSubmit={(event) => {
          event.preventDefault();
          if (!text.trim()) return;
          setMessage(text.trim());
          setText("");
          setStatus("消息已发送到本地演示");
        }}
      >
        <input
          aria-label="输入消息"
          maxLength={160}
          placeholder="输入一条消息…"
          value={text}
          onChange={(event) => setText(event.target.value)}
        />
        <button type="submit" disabled={!text.trim()}>
          发送
        </button>
      </form>
      <button
        type="button"
        onClick={async () => {
          try {
            await navigator.clipboard.writeText(message);
            setStatus("已复制消息");
          } catch {
            setStatus("无法复制，请手动选择消息文字");
          }
        }}
      >
        复制消息
      </button>
      <p role="status">{status || "消息仅在当前演示中展示"}</p>
    </div>
  );
}
` },
      { name: "styles.css", language: "css", code: styles },
    ],
  },
  "message-scroller": {
    vanilla: [
      { name: "index.html", language: "html", code: `<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <section class="modern-demo">
      <div
        class="modern-transcript"
        role="log"
        aria-label="示例消息记录"
        aria-relevant="additions"
        tabindex="0"
      >
        <p>开始整理组件目录</p>
        <p>确认输入与选择的区别</p>
        <p>补充键盘操作说明</p>
        <p>检查可复制代码</p>
        <p>欢迎继续讨论</p>
      </div>
      <div class="modern-actions">
        <button id="add">添加消息</button><button id="latest" hidden>查看新消息 ↓</button>
      </div>
      <p id="status" role="status">正在跟随最新消息</p>
    </section>
    <script src="script.js" defer></script>
  </body>
</html>
` },
      { name: "styles.css", language: "css", code: styles },
      { name: "script.js", language: "js", code: `const log = document.querySelector("[role=log]");
const latest = document.querySelector("#latest");
const status = document.querySelector("#status");
let follow = true;
log.scrollTop = log.scrollHeight;
log.onscroll = () => {
  follow = log.scrollHeight - log.scrollTop - log.clientHeight < 24;
  if (follow) {
    latest.hidden = true;
    status.textContent = "正在跟随最新消息";
  }
};
document.querySelector("#add").onclick = () => {
  const message = document.createElement("p");
  message.textContent = "新的组件笔记 " + (log.children.length + 1);
  log.append(message);
  if (follow) log.scrollTop = log.scrollHeight;
  else {
    latest.hidden = false;
    status.textContent = "已保留你正在阅读的位置";
  }
  if (log.children.length >= 50) document.querySelector("#add").disabled = true;
};
latest.onclick = () => {
  follow = true;
  log.scrollTop = log.scrollHeight;
  latest.hidden = true;
  status.textContent = "正在跟随最新消息";
};
` },
    ],
    react: [
      { name: "Component.jsx", language: "jsx", code: `import { useEffect, useId, useRef, useState } from "react";
import "./styles.css";

export default function MessageScrollerDemo() {
  const [messages, setMessages] = useState([
    "开始整理组件目录",
    "确认输入与选择的区别",
    "补充键盘操作说明",
    "检查可复制代码",
    "欢迎继续讨论",
  ]);
  const [unread, setUnread] = useState(0);
  const viewport = useRef(null);
  const following = useRef(true);
  useEffect(() => {
    if (following.current && viewport.current)
      viewport.current.scrollTop = viewport.current.scrollHeight;
  }, [messages]);
  return (
    <div className="modern-demo">
      <div
        className="modern-transcript"
        ref={viewport}
        role="log"
        aria-label="示例消息记录"
        aria-relevant="additions"
        tabIndex={0}
        onScroll={() => {
          const element = viewport.current;
          if (element) {
            following.current =
              element.scrollHeight - element.scrollTop - element.clientHeight < 24;
            if (following.current) setUnread(0);
          }
        }}
      >
        {messages.map((message, index) => (
          <p key={index}>
            <small>讨论 {String(index + 1).padStart(2, "0")}</small>
            {message}
          </p>
        ))}
      </div>
      <div className="modern-actions">
        <button
          type="button"
          disabled={messages.length >= 50}
          onClick={() => {
            setMessages((current) => [...current, \`新的组件笔记 \${current.length + 1}\`]);
            if (!following.current) setUnread((current) => current + 1);
          }}
        >
          添加消息
        </button>
        {unread > 0 && (
          <button
            type="button"
            onClick={() => {
              following.current = true;
              if (viewport.current)
                viewport.current.scrollTop = viewport.current.scrollHeight;
              setUnread(0);
            }}
          >
            查看新消息 ({unread}) ↓
          </button>
        )}
      </div>
      <p role="status">
        {messages.length >= 50
          ? "演示已达 50 条消息，可重置继续"
          : unread > 0
            ? "已保留你正在阅读的位置"
            : "正在跟随最新消息"}
      </p>
    </div>
  );
}
` },
      { name: "styles.css", language: "css", code: styles },
    ],
  },
  "attachment": {
    vanilla: [
      { name: "index.html", language: "html", code: `<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <section class="modern-demo">
      <article class="modern-attachment">
        <span class="modern-filetype" aria-hidden="true">TXT</span>
        <div><strong>组件笔记.txt</strong><small>纯文本 · 本地示例</small></div>
        <button id="remove" aria-label="移除组件笔记.txt">×</button>
      </article>
      <button id="toggle" aria-expanded="false" aria-controls="preview">
        预览组件笔记
      </button>
      <div id="preview" hidden>附件展示文件名称与状态；文件上传负责选择和提交文件。</div>
      <button id="restore" hidden>恢复附件</button>
      <p id="status" role="status"></p>
    </section>
    <script src="script.js" defer></script>
  </body>
</html>
` },
      { name: "styles.css", language: "css", code: styles },
      { name: "script.js", language: "js", code: `const toggle = document.querySelector("#toggle");
const preview = document.querySelector("#preview");
const restore = document.querySelector("#restore");
toggle.onclick = () => {
  preview.hidden = !preview.hidden;
  toggle.setAttribute("aria-expanded", String(!preview.hidden));
};
document.querySelector("#remove").onclick = () => {
  document.querySelector("article").hidden = true;
  toggle.hidden = true;
  preview.hidden = true;
  toggle.setAttribute("aria-expanded", "false");
  restore.hidden = false;
  document.querySelector("#status").textContent = "已移除组件笔记";
  restore.focus();
};
restore.onclick = () => {
  document.querySelector("article").hidden = false;
  toggle.hidden = false;
  restore.hidden = true;
  document.querySelector("#status").textContent = "已恢复附件";
  toggle.focus();
};
` },
    ],
    react: [
      { name: "Component.jsx", language: "jsx", code: `import { useEffect, useId, useRef, useState } from "react";
import "./styles.css";

export default function AttachmentDemo() {
  const [removed, setRemoved] = useState(false);
  const [expanded, setExpanded] = useState(false);
  const id = useId();
  const restore = useRef(null);
  const preview = useRef(null);
  const changed = useRef(false);
  useEffect(() => {
    if (changed.current) (removed ? restore : preview).current?.focus();
  }, [removed]);
  return (
    <div className="modern-demo">
      <div className="modern-kicker">消息附件</div>
      {removed ? (
        <p role="status">已移除组件笔记</p>
      ) : (
        <article className="modern-attachment">
          <span className="modern-filetype" aria-hidden="true">
            TXT
          </span>
          <div>
            <strong>组件笔记.txt</strong>
            <small>纯文本 · 本地示例</small>
          </div>
          <button
            type="button"
            aria-label="移除组件笔记.txt"
            onClick={() => {
              changed.current = true;
              setRemoved(true);
              setExpanded(false);
            }}
          >
            ×
          </button>
        </article>
      )}
      {!removed && (
        <button
          ref={preview}
          type="button"
          aria-expanded={expanded}
          aria-controls={\`\${id}-preview\`}
          onClick={() => setExpanded((current) => !current)}
        >
          {expanded ? "收起预览" : "预览组件笔记"}
        </button>
      )}
      <div id={\`\${id}-preview\`} hidden={!expanded || removed}>
        <p>附件展示文件名称与状态；文件上传负责选择和提交文件。</p>
      </div>
      {removed && (
        <button ref={restore} type="button" onClick={() => setRemoved(false)}>
          恢复附件
        </button>
      )}
    </div>
  );
}
` },
      { name: "styles.css", language: "css", code: styles },
    ],
  },
};
